import {
  AlignmentType,
  BorderStyle,
  Document,
  Footer,
  Header,
  ImageRun,
  LevelFormat,
  LineRuleType,
  Packer,
  PageBreak,
  Paragraph,
  ShadingType,
  SimpleField,
  Table,
  TableCell,
  TableLayoutType,
  TableRow,
  TextRun,
  VerticalAlign,
  WidthType
} from "docx";
import PDFDocument from "pdfkit";
import JSZip from "jszip";
import { normalizeDocumentSpec } from "./documentSpec.js";

const DOCX_PAGE_WIDTH = 12_240;
const DOCX_MARGIN = 1_440;
const DOCX_CONTENT_WIDTH = DOCX_PAGE_WIDTH - (DOCX_MARGIN * 2);
const PDF_PAGE_WIDTH = 612;
const PDF_PAGE_HEIGHT = 792;
const PDF_MARGIN = 64;

const THEMES = Object.freeze({
  business: {
    font: "Calibri",
    accent: "1F4E78",
    accentLight: "EAF2F8",
    text: "1F2937",
    muted: "64748B",
    line: "CBD5E1",
    titleSize: 42,
    bodySize: 10.5,
    lineGap: 3
  },
  compact: {
    font: "Calibri",
    accent: "0F766E",
    accentLight: "E6FFFA",
    text: "17202A",
    muted: "5B6770",
    line: "CBD5E1",
    titleSize: 36,
    bodySize: 9.5,
    lineGap: 2
  },
  proposal: {
    font: "Calibri",
    accent: "7C3E21",
    accentLight: "FFF3E8",
    text: "2D2926",
    muted: "6B625D",
    line: "D8CFC8",
    titleSize: 44,
    bodySize: 10.5,
    lineGap: 3
  }
});

export async function renderDocumentArtifact(input, format, { assets = null } = {}) {
  const spec = normalizeDocumentSpec(input);
  if (format === "docx") return renderDocx(spec, assets);
  if (format === "pdf") return renderPdf(spec, assets);
  throw new Error(`Unsupported document format: ${format}`);
}

async function renderDocx(spec, assets) {
  const theme = resolvedTheme(spec);
  const children = [docxLayoutAnchor()];
  if (assets?.logo) {
    children.push(docxVisualParagraph(assets.logo, {
      altText: `${spec.brand?.name || spec.title} logo`,
      width: 140,
      alignment: AlignmentType.LEFT,
      spacingAfter: 180,
      keepNext: true
    }));
  }
  children.push(
    new Paragraph({
      style: "AmosTitle",
      children: [new TextRun(spec.title)]
    })
  );
  if (spec.subtitle) {
    children.push(new Paragraph({
      style: "AmosSubtitle",
      children: [new TextRun(spec.subtitle)]
    }));
  }
  if (spec.author) {
    children.push(new Paragraph({
      style: "AmosMetadata",
      children: [new TextRun(spec.author)]
    }));
  }
  spec.blocks.forEach((block, index) => {
    if (block.type === "page_break") {
      children.push(new Paragraph({
        spacing: { before: 0, after: 0 },
        children: [new PageBreak()]
      }));
      children.push(docxLayoutAnchor());
      return;
    }
    const asset = block.type === "image"
      ? assets?.images?.get(block.path)
      : block.type === "chart"
        ? assets?.charts?.get(index)
        : null;
    children.push(...docxBlock(block, theme, asset));
  });
  const document = new Document({
    creator: spec.author || "AMOS Desktop",
    title: spec.title,
    subject: spec.subject || "Generated by AMOS Desktop",
    description: `Generated from amos.document-spec version ${spec.version}`,
    styles: docxStyles(theme),
    numbering: {
      config: [
        {
          reference: "amos-bullets",
          levels: [{
            level: 0,
            format: LevelFormat.BULLET,
            text: "•",
            alignment: AlignmentType.LEFT,
            style: { paragraph: { indent: { left: 720, hanging: 360 } } }
          }]
        },
        {
          reference: "amos-numbered",
          levels: [{
            level: 0,
            format: LevelFormat.DECIMAL,
            text: "%1.",
            alignment: AlignmentType.LEFT,
            style: { paragraph: { indent: { left: 720, hanging: 360 } } }
          }]
        },
        {
          reference: "amos-sources",
          levels: [{
            level: 0,
            format: LevelFormat.DECIMAL,
            text: "%1.",
            alignment: AlignmentType.LEFT,
            style: { paragraph: { indent: { left: 720, hanging: 360 } } }
          }]
        }
      ]
    },
    sections: [{
      properties: {
        page: {
          size: { width: DOCX_PAGE_WIDTH, height: 15_840 },
          margin: {
            top: DOCX_MARGIN,
            right: DOCX_MARGIN,
            bottom: DOCX_MARGIN,
            left: DOCX_MARGIN
          }
        }
      },
      headers: spec.header ? {
        default: docxHeader(spec.header, theme)
      } : undefined,
      footers: {
        default: docxFooter(spec, theme)
      },
      children
    }]
  });
  return removeDisabledEvenOddHeaders(await Packer.toBuffer(document));
}

function docxLayoutAnchor() {
  // Forces interoperable top margins when LibreOffice paginates OOXML headers.
  return new Paragraph({
    spacing: { before: 0, after: 0, line: 240, lineRule: LineRuleType.EXACT },
    children: [new TextRun({ text: ".", color: "FFFFFF", size: 8 })]
  });
}

async function removeDisabledEvenOddHeaders(buffer) {
  // docx writes an explicit false element that LibreOffice treats as enabled.
  const zip = await JSZip.loadAsync(buffer);
  const settingsFile = zip.file("word/settings.xml");
  if (!settingsFile) return buffer;
  const settings = await settingsFile.async("string");
  const normalized = settings.replace(
    /<w:evenAndOddHeaders\s+w:val="(?:false|0|off|no)"\s*\/>/g,
    ""
  );
  if (normalized === settings) return buffer;
  zip.file("word/settings.xml", normalized);
  return zip.generateAsync({ type: "nodebuffer", compression: "DEFLATE" });
}

function docxHeader(text, theme) {
  return new Header({
    children: [new Paragraph({
      border: { bottom: { color: theme.line, style: BorderStyle.SINGLE, size: 4, space: 5 } },
      children: [new TextRun({ text, color: theme.muted, size: 16 })]
    })]
  });
}

function docxFooter(spec, theme) {
  return new Footer({
    children: [new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 0, after: 0 },
      children: [
        new TextRun({ text: `${spec.footer || spec.title}  |  `, color: theme.muted, size: 16 }),
        new SimpleField("PAGE", "1")
      ]
    })]
  });
}

function docxStyles(theme) {
  return {
    default: {
      document: {
        run: { font: theme.font, size: 22, color: theme.text },
        paragraph: { spacing: { after: 120, line: 264 } }
      }
    },
    paragraphStyles: [
      {
        id: "AmosTitle",
        name: "AMOS Title",
        basedOn: "Normal",
        next: "Normal",
        quickFormat: true,
        run: { font: theme.font, size: theme.titleSize * 2, bold: true, color: theme.accent },
        paragraph: {
          spacing: { before: 0, after: 160, line: 1_000, lineRule: LineRuleType.EXACT }
        }
      },
      {
        id: "AmosSubtitle",
        name: "AMOS Subtitle",
        basedOn: "Normal",
        next: "Normal",
        quickFormat: true,
        run: { font: theme.font, size: 28, color: theme.muted },
        paragraph: {
          spacing: { before: 0, after: 200, line: 420, lineRule: LineRuleType.EXACT }
        }
      },
      {
        id: "AmosMetadata",
        name: "AMOS Metadata",
        basedOn: "Normal",
        next: "Normal",
        run: { font: theme.font, size: 18, color: theme.muted, italics: true },
        paragraph: {
          spacing: { before: 0, after: 280, line: 280, lineRule: LineRuleType.EXACT }
        }
      },
      ...[1, 2, 3].map((level) => ({
        id: `AmosHeading${level}`,
        name: `AMOS Heading ${level}`,
        basedOn: "Normal",
        next: "Normal",
        quickFormat: true,
        run: {
          font: theme.font,
          size: [32, 27, 23][level - 1],
          bold: true,
          color: level === 1 ? theme.accent : theme.text
        },
        paragraph: {
          keepNext: true,
          spacing: { before: [320, 260, 220][level - 1], after: 100 }
        }
      }))
    ]
  };
}

function docxBlock(block, theme, asset = null) {
  if (block.type === "heading") {
    return [new Paragraph({
      style: `AmosHeading${block.level}`,
      children: [new TextRun(block.text)]
    })];
  }
  if (block.type === "paragraph") {
    return block.text.split(/\n{2,}/).map((value) => new Paragraph({
      children: [new TextRun(value.replace(/\n/g, " "))]
    }));
  }
  if (block.type === "list") {
    const reference = block.style === "numbered" ? "amos-numbered" : "amos-bullets";
    return block.items.map((item) => new Paragraph({
      numbering: { reference, level: 0 },
      spacing: { after: 80 },
      children: [new TextRun(item)]
    }));
  }
  if (block.type === "table") {
    return [docxTable(block, theme)];
  }
  if (block.type === "callout") {
    const label = block.label ? `${block.label}: ` : "";
    return [new Paragraph({
      shading: { type: ShadingType.CLEAR, fill: theme.accentLight },
      border: {
        left: { color: theme.accent, style: BorderStyle.SINGLE, size: 18, space: 8 }
      },
      indent: { left: 180, right: 180 },
      spacing: { before: 160, after: 200, line: 300 },
      children: [
        new TextRun({ text: label, bold: Boolean(label), color: theme.accent }),
        new TextRun(block.text)
      ]
    })];
  }
  if (["image", "chart"].includes(block.type)) {
    if (!asset) throw new Error(`Document ${block.type} asset was not resolved`);
    const altText = block.alt_text;
    return [
      docxVisualParagraph(asset, {
        altText,
        width: block.type === "image" ? Math.round(624 * (block.width_percent / 100)) : 624,
        alignment: AlignmentType.CENTER,
        spacingAfter: block.caption ? 60 : 180,
        keepNext: Boolean(block.caption)
      }),
      ...(block.caption ? [new Paragraph({
        alignment: AlignmentType.CENTER,
        spacing: { before: 0, after: 180 },
        children: [new TextRun({ text: block.caption, color: theme.muted, italics: true, size: 18 })]
      })] : [])
    ];
  }
  if (block.type === "sources") {
    return [
      new Paragraph({
        style: "AmosHeading2",
        children: [new TextRun("Sources")]
      }),
      ...block.sources.map((source) => new Paragraph({
        numbering: { reference: "amos-sources", level: 0 },
        spacing: { after: 80 },
        children: [new TextRun(sourceLine(source))]
      }))
    ];
  }
  throw new Error(`Unsupported DOCX block type: ${block.type}`);
}

function docxVisualParagraph(asset, {
  altText,
  width,
  alignment,
  spacingAfter,
  keepNext = false
}) {
  const height = Math.max(1, Math.round(width * (asset.height / asset.width)));
  return new Paragraph({
    alignment,
    keepNext,
    spacing: { before: 120, after: spacingAfter },
    children: [new ImageRun({
      type: asset.type,
      data: asset.data,
      transformation: { width, height },
      altText: {
        name: altText.slice(0, 120),
        title: altText.slice(0, 200),
        description: altText
      }
    })]
  });
}

function docxTable(block, theme) {
  const columnWidths = tableColumnWidths(block);
  const borders = {
    top: { style: BorderStyle.SINGLE, color: theme.line, size: 4 },
    bottom: { style: BorderStyle.SINGLE, color: theme.line, size: 4 },
    left: { style: BorderStyle.SINGLE, color: theme.line, size: 4 },
    right: { style: BorderStyle.SINGLE, color: theme.line, size: 4 },
    insideHorizontal: { style: BorderStyle.SINGLE, color: theme.line, size: 4 },
    insideVertical: { style: BorderStyle.SINGLE, color: theme.line, size: 4 }
  };
  const row = (cells, header = false) => new TableRow({
    tableHeader: header,
    children: cells.map((cell, index) => new TableCell({
      width: { size: columnWidths[index], type: WidthType.DXA },
      verticalAlign: VerticalAlign.CENTER,
      margins: { top: 120, bottom: 120, left: 120, right: 120 },
      shading: header ? { type: ShadingType.CLEAR, fill: theme.accent } : undefined,
      children: [new Paragraph({
        spacing: { before: 0, after: 0, line: 250 },
        children: [new TextRun({
          text: cell || " ",
          bold: header,
          color: header ? "FFFFFF" : theme.text,
          size: 18
        })]
      })]
    }))
  });
  return new Table({
    width: { size: DOCX_CONTENT_WIDTH, type: WidthType.DXA },
    columnWidths,
    layout: TableLayoutType.FIXED,
    borders,
    rows: [row(block.headers, true), ...block.rows.map((cells) => row(cells))]
  });
}

function tableColumnWidths(block) {
  const weights = block.headers.map((header, index) => {
    const body = block.rows.slice(0, 50).map((row) => row[index]?.length || 0);
    return Math.max(6, Math.min(40, Math.max(header.length, ...body)));
  });
  const total = weights.reduce((sum, value) => sum + value, 0);
  const widths = weights.map((weight) => Math.floor((weight / total) * DOCX_CONTENT_WIDTH));
  widths[widths.length - 1] += DOCX_CONTENT_WIDTH - widths.reduce((sum, value) => sum + value, 0);
  return widths;
}

function renderPdf(spec, assets) {
  const theme = resolvedTheme(spec);
  return new Promise((resolve, reject) => {
    const chunks = [];
    const pdf = new PDFDocument({
      size: "LETTER",
      margins: { top: PDF_MARGIN, right: PDF_MARGIN, bottom: PDF_MARGIN, left: PDF_MARGIN },
      bufferPages: true,
      info: {
        Title: spec.title,
        Author: spec.author || "AMOS Desktop",
        Subject: spec.subject || "Generated by AMOS Desktop",
        Creator: "AMOS Desktop",
        CreationDate: new Date(0),
        ModDate: new Date(0)
      }
    });
    pdf.on("data", (chunk) => chunks.push(chunk));
    pdf.on("error", reject);
    pdf.on("end", () => resolve(Buffer.concat(chunks)));

    if (assets?.logo) {
      const dimensions = fitDimensions(assets.logo, 140, 60);
      pdf.image(assets.logo.data, PDF_MARGIN, pdf.y, dimensions);
      pdf.y += dimensions.height + 18;
    }
    pdf.font("Helvetica-Bold").fontSize(theme.titleSize).fillColor(`#${theme.accent}`)
      .text(spec.title, { lineGap: 2 });
    if (spec.subtitle) {
      pdf.moveDown(0.25).font("Helvetica").fontSize(14).fillColor(`#${theme.muted}`)
        .text(spec.subtitle, { lineGap: 2 });
    }
    if (spec.author) {
      pdf.moveDown(0.45).font("Helvetica-Oblique").fontSize(9).fillColor(`#${theme.muted}`)
        .text(spec.author);
    }
    pdf.moveDown(0.7);
    pdf.strokeColor(`#${theme.line}`).lineWidth(1)
      .moveTo(PDF_MARGIN, pdf.y).lineTo(PDF_PAGE_WIDTH - PDF_MARGIN, pdf.y).stroke();
    pdf.moveDown(0.8);

    spec.blocks.forEach((block, index) => {
      const asset = block.type === "image"
        ? assets?.images?.get(block.path)
        : block.type === "chart"
          ? assets?.charts?.get(index)
          : null;
      renderPdfBlock(pdf, block, theme, asset);
    });
    const range = pdf.bufferedPageRange();
    for (let index = range.start; index < range.start + range.count; index += 1) {
      pdf.switchToPage(index);
      const bottomMargin = pdf.page.margins.bottom;
      pdf.page.margins.bottom = 0;
      pdf.font("Helvetica").fontSize(8).fillColor(`#${theme.muted}`)
        .text(
          `${spec.footer || spec.title}  |  ${index - range.start + 1} / ${range.count}`,
          PDF_MARGIN,
          PDF_PAGE_HEIGHT - 38,
          { width: PDF_PAGE_WIDTH - (PDF_MARGIN * 2), align: "center", lineBreak: false }
        );
      pdf.page.margins.bottom = bottomMargin;
    }
    pdf.end();
  });
}

function renderPdfBlock(pdf, block, theme, asset = null) {
  if (block.type === "page_break") {
    pdf.addPage();
    return;
  }
  if (block.type === "heading") {
    const sizes = [20, 15, 12];
    const before = [28, 20, 16];
    const size = sizes[block.level - 1];
    const height = pdf.font("Helvetica-Bold").fontSize(size).heightOfString(block.text, {
      width: contentWidth()
    });
    ensurePdfSpace(pdf, height + before[block.level - 1]);
    pdf.moveDown(block.level === 1 ? 0.9 : 0.6)
      .fillColor(block.level === 1 ? `#${theme.accent}` : `#${theme.text}`)
      .text(block.text, { lineGap: 2 });
    pdf.moveDown(0.3);
    return;
  }
  if (block.type === "paragraph") {
    for (const paragraph of block.text.split(/\n{2,}/)) {
      pdf.font("Helvetica").fontSize(theme.bodySize).fillColor(`#${theme.text}`);
      const value = paragraph.replace(/\n/g, " ");
      ensurePdfSpace(pdf, pdf.heightOfString(value, { width: contentWidth(), lineGap: theme.lineGap }) + 8);
      pdf.text(value, { lineGap: theme.lineGap });
      pdf.moveDown(0.55);
    }
    return;
  }
  if (block.type === "list") {
    block.items.forEach((item, index) => {
      pdf.font("Helvetica").fontSize(theme.bodySize).fillColor(`#${theme.text}`);
      const marker = block.style === "numbered" ? `${index + 1}.` : "•";
      const itemWidth = contentWidth() - 24;
      const height = pdf.heightOfString(item, { width: itemWidth, lineGap: theme.lineGap });
      ensurePdfSpace(pdf, height + 8);
      const y = pdf.y;
      pdf.font("Helvetica-Bold").text(marker, PDF_MARGIN, y, { width: 18, lineBreak: false });
      pdf.font("Helvetica").text(item, PDF_MARGIN + 24, y, { width: itemWidth, lineGap: theme.lineGap });
      pdf.y = Math.max(pdf.y, y + height) + 5;
    });
    pdf.moveDown(0.25);
    return;
  }
  if (block.type === "table") {
    renderPdfTable(pdf, block, theme);
    return;
  }
  if (block.type === "callout") {
    pdf.font("Helvetica").fontSize(theme.bodySize);
    const label = block.label ? `${block.label}: ` : "";
    const value = `${label}${block.text}`;
    const height = pdf.heightOfString(value, { width: contentWidth() - 28, lineGap: theme.lineGap }) + 22;
    ensurePdfSpace(pdf, height + 12);
    const y = pdf.y;
    pdf.save().fillColor(`#${theme.accentLight}`).rect(PDF_MARGIN, y, contentWidth(), height).fill();
    pdf.fillColor(`#${theme.accent}`).rect(PDF_MARGIN, y, 4, height).fill().restore();
    pdf.fillColor(`#${theme.text}`).font("Helvetica").fontSize(theme.bodySize)
      .text(value, PDF_MARGIN + 16, y + 11, { width: contentWidth() - 28, lineGap: theme.lineGap });
    pdf.y = y + height + 14;
    return;
  }
  if (["image", "chart"].includes(block.type)) {
    if (!asset) throw new Error(`Document ${block.type} asset was not resolved`);
    const maximumWidth = block.type === "image"
      ? contentWidth() * (block.width_percent / 100)
      : contentWidth();
    const dimensions = fitDimensions(asset, maximumWidth, 330);
    const captionHeight = block.caption ? 34 : 0;
    ensurePdfSpace(pdf, dimensions.height + captionHeight + 24);
    const x = PDF_MARGIN + ((contentWidth() - dimensions.width) / 2);
    pdf.image(asset.data, x, pdf.y, dimensions);
    pdf.y += dimensions.height + 7;
    if (block.caption) {
      pdf.font("Helvetica-Oblique").fontSize(8.5).fillColor(`#${theme.muted}`)
        .text(block.caption, PDF_MARGIN, pdf.y, { width: contentWidth(), align: "center", lineGap: 2 });
      pdf.moveDown(0.65);
    } else {
      pdf.moveDown(0.8);
    }
    return;
  }
  if (block.type === "sources") {
    renderPdfBlock(pdf, { type: "heading", level: 2, text: "Sources" }, theme);
    renderPdfBlock(pdf, {
      type: "list",
      style: "numbered",
      items: block.sources.map(sourceLine)
    }, theme);
  }
}

function renderPdfTable(pdf, block, theme) {
  const weights = tableColumnWidths(block);
  const widths = weights.map((width) => (width / DOCX_CONTENT_WIDTH) * contentWidth());
  const renderRow = (cells, header) => {
    pdf.font(header ? "Helvetica-Bold" : "Helvetica").fontSize(8.5);
    const heights = cells.map((cell, index) => pdf.heightOfString(cell || " ", {
      width: widths[index] - 12,
      lineGap: 2
    }));
    const rowHeight = Math.max(26, Math.max(...heights) + 12);
    if (pdf.y + rowHeight > PDF_PAGE_HEIGHT - PDF_MARGIN - 18) {
      pdf.addPage();
      if (!header) renderRow(block.headers, true);
    }
    let x = PDF_MARGIN;
    const y = pdf.y;
    cells.forEach((cell, index) => {
      pdf.save();
      pdf.fillColor(header ? `#${theme.accent}` : "#FFFFFF")
        .strokeColor(`#${theme.line}`)
        .rect(x, y, widths[index], rowHeight)
        .fillAndStroke();
      pdf.fillColor(header ? "#FFFFFF" : `#${theme.text}`)
        .font(header ? "Helvetica-Bold" : "Helvetica")
        .fontSize(8.5)
        .text(cell || " ", x + 6, y + 6, { width: widths[index] - 12, lineGap: 2 });
      pdf.restore();
      x += widths[index];
    });
    pdf.y = y + rowHeight;
  };
  ensurePdfSpace(pdf, 52);
  renderRow(block.headers, true);
  block.rows.forEach((row) => renderRow(row, false));
  pdf.moveDown(0.8);
}

function ensurePdfSpace(pdf, height) {
  if (pdf.y + height > PDF_PAGE_HEIGHT - PDF_MARGIN - 18) pdf.addPage();
}

function contentWidth() {
  return PDF_PAGE_WIDTH - (PDF_MARGIN * 2);
}

function sourceLine(source) {
  const reference = source.url || source.source_ref;
  const second = source.url && source.source_ref ? ` (${source.source_ref})` : "";
  return `${source.label} - ${reference}${second}`;
}

function resolvedTheme(spec) {
  const base = THEMES[spec.style];
  return {
    ...base,
    accent: spec.brand?.primary_color || base.accent,
    accentLight: spec.brand?.secondary_color || base.accentLight,
    text: spec.brand?.text_color || base.text
  };
}

function fitDimensions(asset, maximumWidth, maximumHeight) {
  const scale = Math.min(maximumWidth / asset.width, maximumHeight / asset.height, 1);
  return {
    width: Math.max(1, Math.round(asset.width * scale)),
    height: Math.max(1, Math.round(asset.height * scale))
  };
}
