variable "aws_region" {
  description = "AWS region for the private inference cell."
  type        = string
  default     = "us-east-1"
}

variable "availability_zone" {
  description = "Availability zone that offers the selected GPU instance."
  type        = string
  default     = "us-east-1b"
}

variable "environment" {
  description = "Short environment label used in names and tags."
  type        = string
  default     = "research"

  validation {
    condition     = can(regex("^[a-z][a-z0-9-]{1,20}$", var.environment))
    error_message = "environment must be a short lowercase identifier."
  }
}

variable "inference_enabled" {
  description = "Create the paid GPU instance only after the image and model are staged."
  type        = bool
  default     = false
}

variable "instance_type" {
  description = "Single-GPU instance for the first inference cell."
  type        = string
  default     = "g7e.2xlarge"
}

variable "ami_id" {
  description = "Pinned AWS Deep Learning Base OSS Nvidia Driver AMI ID."
  type        = string
  default     = ""

  validation {
    condition     = var.ami_id == "" || can(regex("^ami-[a-f0-9]+$", var.ami_id))
    error_message = "ami_id must be empty or a valid AMI ID."
  }
}

variable "root_volume_gib" {
  description = "Encrypted gp3 capacity for the OS, container layers, and staged model."
  type        = number
  default     = 300
}

variable "vllm_image_uri" {
  description = "Private ECR vLLM image URI pinned with @sha256:..."
  type        = string
  default     = ""

  validation {
    condition     = var.vllm_image_uri == "" || can(regex("@sha256:[a-f0-9]{64}$", var.vllm_image_uri))
    error_message = "vllm_image_uri must be empty or an immutable ECR digest."
  }
}

variable "model_repository" {
  description = "Auditable upstream model repository."
  type        = string
  default     = "Qwen/Qwen3.8-27B-FP8"
}

variable "model_revision" {
  description = "Exact upstream Qwen commit staged in the private model bucket."
  type        = string
  default     = "017b9c7af6b5689d5dd426a76e0bc077eb5ca20a"

  validation {
    condition     = can(regex("^[a-f0-9]{40}$", var.model_revision))
    error_message = "model_revision must be a full 40-character Git commit."
  }
}

variable "model_manifest_sha256" {
  description = "SHA-256 of model-manifest.sha256 generated by stage-model.sh."
  type        = string
  default     = ""

  validation {
    condition     = var.model_manifest_sha256 == "" || can(regex("^[a-f0-9]{64}$", var.model_manifest_sha256))
    error_message = "model_manifest_sha256 must be empty or a lowercase SHA-256 digest."
  }
}

variable "served_model_name" {
  description = "Stable model name exposed by the private OpenAI-compatible endpoint."
  type        = string
  default     = "amos-qwen38-27b-fp8"
}

variable "max_model_len" {
  description = "Initial context ceiling; increase only after memory qualification."
  type        = number
  default     = 32768
}

variable "max_num_seqs" {
  description = "Concurrent logical worker sequences admitted by vLLM."
  type        = number
  default     = 8
}

variable "max_num_batched_tokens" {
  description = "Continuous-batching token budget."
  type        = number
  default     = 16384
}

variable "gpu_memory_utilization" {
  description = "vLLM GPU memory fraction; leaves headroom for warmup and MTP."
  type        = number
  default     = 0.85
}

variable "mtp_speculative_tokens" {
  description = "Native Qwen MTP draft tokens verified losslessly by the target model."
  type        = number
  default     = 3
}

variable "monthly_budget_usd" {
  description = "Optional AWS Budget threshold. Zero disables budget creation."
  type        = number
  default     = 0
}

variable "budget_email" {
  description = "Email notified at 50, 80, and 100 percent of the optional monthly budget."
  type        = string
  default     = ""

  validation {
    condition     = var.budget_email == "" || can(regex("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$", var.budget_email))
    error_message = "budget_email must be empty or a valid email address."
  }
}
